# Disable automatic builds
# Without this, the following error shows up:
# "Specify a project or solution file. The directory does not contain a project or solution file."
build: off

# version format
version: 0.0.0.{build}

# Ignore testing a commit if only the README.md file changed
# Or if various strings are found in the commit message: updated readme, update readme, update docs, update version, update appveyor
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

# PowerShell Gallery API key for publishing an update to the module
environment:
  GitHubKey:
    secure: /eAcJvMF10bbDW9YEf2BsZ+vXbaz2UqUJiTRpzZFWWYw8k5QogfgF8kmqigmuMBZ
  NuGetApiKey:
    secure: 8fzPA9jCuntNmDKjf/RWRvEQuqqsuMNJ7ywZ2hIWnbrETAWc9JtW3PnhEhnRXaIU

# Install NuGet to interact with the PowerShell Gallery
install:
  - ps: . .\build\InstallDependancies.ps1

